server:
  port: 8099
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee?charsetEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      initial-size: 8
      max-active: 50
      min-idle: 8
      max-wait: 6000
mybatis-plus:
  type-aliases-package: com.drink.coffee.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.drink.coffee.mapper: debug
